#!/sbin/openrc-run
#
# Sample init.d file for jitsi-videobridge

description="jitsi-videobridge"
description_checkconfig="verify configuration file"
description_reload="Reload configuration"

name="jitsi-videobridge"
command="/usr/bin/java"
command_args="$sample_opts"
command_background="yes"

start_stop_daemon_args="--user $sample_user:$sample_group"
pidfile="/run/$name.pid"

depend() {
	need net
	after firewall
}
